/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone_18_pro_max.glb -t 
Author: TechFreak (https://sketchfab.com/Tech_Freak-2511)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-18-pro-max-7e9f699aeccf460b97782fbbdb56ba2a
Title: iphone 18 pro max
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useTexture } from "@react-three/drei";

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
  }
  materials: {
    ['17ProMax_glass']: THREE.MeshPhysicalMaterial
    ['17ProMax_color']: THREE.MeshStandardMaterial
    ['17ProMax_Black2']: THREE.MeshStandardMaterial
    ['17ProMax_color3']: THREE.MeshStandardMaterial
    ['17ProMax_color2']: THREE.MeshStandardMaterial
    ['17ProMax_black1']: THREE.MeshStandardMaterial
    ['17ProMax_G']: THREE.MeshStandardMaterial
    ['17ProMax_Lens']: THREE.MeshStandardMaterial
    ['17ProMax_Screen.001']: THREE.MeshStandardMaterial
    ['17ProMax_21']: THREE.MeshStandardMaterial
    ['17ProMax_22']: THREE.MeshStandardMaterial
    ['17ProMax_Logo']: THREE.MeshStandardMaterial
    ['17ProMax_1111']: THREE.MeshStandardMaterial
    ['17ProMax_2222']: THREE.MeshStandardMaterial
    ['17ProMax_Black2.001']: THREE.MeshStandardMaterial
    ['17ProMax_2112.001']: THREE.MeshStandardMaterial
    ['17ProMax_Lens2.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[];
}

export function IphoneModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/iphone_18_pro_max.glb') as unknown as GLTFResult;

const screen = useTexture("/AC.png");
console.log(nodes.Object_15.geometry.attributes.uv);

  return (
    <group {...props} dispose={null}>
      <group position={[-0.489, 1.49, 0.48]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_7.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['17ProMax_Black2']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['17ProMax_color3']} />
        {/* <mesh geometry={nodes.Object_10.geometry} material={materials['17ProMax_glass']} /> */}
        <mesh geometry={nodes.Object_11.geometry} material={materials['17ProMax_color2']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['17ProMax_black1']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['17ProMax_G']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['17ProMax_Lens']} />
       
<mesh geometry={nodes.Object_15.geometry}>
  <meshBasicMaterial map={screen} />
</mesh>
      </group>
      <group position={[-0.261, 2.947, 0.678]} rotation={[1.568, 0, 0]} scale={59.227}>
        <mesh geometry={nodes.Object_17.geometry} material={materials['17ProMax_Black2']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['17ProMax_black1']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['17ProMax_Lens']} />
      </group>
      <group position={[1.391, 3.527, 0.622]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_21.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['17ProMax_glass']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['17ProMax_21']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['17ProMax_22']} />
      </group>
      <group position={[1.391, 2.414, 0.635]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_26.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['17ProMax_Black2']} />
      </group>
      <group position={[-1.26, 2.419, 0.666]} rotation={[1.568, 0, 0]} scale={60.338}>
        <mesh geometry={nodes.Object_29.geometry} material={materials['17ProMax_Black2']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['17ProMax_black1']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['17ProMax_Lens']} />
      </group>
      <group position={[0.395, -4.68, 0.281]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_47.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['17ProMax_1111']} />
      </group>
      <group position={[-0.395, -4.68, 0.281]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_50.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_51.geometry} material={materials['17ProMax_1111']} />
      </group>
      <group position={[-0.975, -4.694, 0.281]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_53.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['17ProMax_Black2']} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['17ProMax_2222']} />
      </group>
      <group position={[0.974, -4.694, 0.281]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_57.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_58.geometry} material={materials['17ProMax_Black2']} />
        <mesh geometry={nodes.Object_59.geometry} material={materials['17ProMax_2222']} />
      </group>
      <group position={[-2.119, -1.891, 0.273]} rotation={[1.568, 0, 0]} scale={55}>
        <mesh geometry={nodes.Object_63.geometry} material={materials['17ProMax_color']} />
        <mesh geometry={nodes.Object_64.geometry} material={materials['17ProMax_color2']} />
      </group>
      <group position={[0, 3.851, -0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={36.172}>
        <mesh geometry={nodes.Object_66.geometry} material={materials['17ProMax_Black2.001']} />
        <mesh geometry={nodes.Object_67.geometry} material={materials['17ProMax_2112.001']} />
      </group>
      <group position={[-0.308, 3.85, -0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={36.172}>
        <mesh geometry={nodes.Object_69.geometry} material={materials['17ProMax_Black2.001']} />
        <mesh geometry={nodes.Object_70.geometry} material={materials['17ProMax_Lens2.001']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials['17ProMax_2112.001']} />
      </group>
      {/* <mesh geometry={nodes.Object_5.geometry} material={materials['17ProMax_glass']} position={[0.08, -0.322, 0]} rotation={[1.568, 0, 0]} scale={55} /> */}
      <mesh geometry={nodes.Object_33.geometry} material={materials['17ProMax_Logo']} position={[0.068, -1.275, 0.512]} rotation={[1.568, 0, 0]} scale={55} />
      <mesh geometry={nodes.Object_35.geometry} material={materials['17ProMax_color']} position={[2.131, 2.395, 0.258]} rotation={[1.568, 0, 0]} scale={55} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['17ProMax_color']} position={[-2.142, 1.687, 0.261]} rotation={[1.568, 0, 0]} scale={55} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['17ProMax_color']} position={[2.131, 0.84, 0.263]} rotation={[1.568, 0, 0]} scale={55} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['17ProMax_color']} position={[2.132, 1.624, 0.261]} rotation={[1.568, 0, 0]} scale={55} />
      <mesh geometry={nodes.Object_43.geometry} material={materials['17ProMax_color']} position={[-2.145, 0.937, 0.261]} rotation={[1.568, 0, 0]} scale={55} />
      <mesh geometry={nodes.Object_45.geometry} material={materials['17ProMax_color2']} position={[0.043, -1.344, 0.512]} rotation={[1.568, 0, 0]} scale={55} />
      <mesh geometry={nodes.Object_61.geometry} material={materials['17ProMax_color']} position={[2.114, -2.671, 0.275]} rotation={[1.568, 0, 0]} scale={55} />
    </group>
  )
}

useGLTF.preload('/iphone_18_pro_max.glb')
