/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 free_ac_unit.glb -t 
Author: vertexmonster (https://sketchfab.com/vertexmonster)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-ac-unit-08223d7724f54639b06cb2b276b6d252
Title: Free AC Unit
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    Bolts: THREE.MeshStandardMaterial
    Cables_And_Power_Switch: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Front_Grill: THREE.MeshStandardMaterial
    Main_Body: THREE.MeshStandardMaterial
    material_5: THREE.MeshStandardMaterial
    Radiator: THREE.MeshStandardMaterial
    Rails: THREE.MeshStandardMaterial
  }
   animations: THREE.AnimationClip[];
}

export default function AcModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/free_ac_unit.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Bolts} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Cables_And_Power_Switch} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Front_Grill} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Main_Body} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Radiator} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Rails} />
      </group>
    </group>
  )
}

useGLTF.preload('/free_ac_unit.glb')
