/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 push-fit_90_elbow.glb -t 
Author: _Bonehead14 (https://sketchfab.com/_Bonehead14)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/push-fit-90-elbow-8be589e023554ebd86b9c975d72609f5
Title: Push-Fit 90° Elbow
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Low_Plastic_0: THREE.Mesh
    Low_Low_0: THREE.Mesh
    Low_Low001_0: THREE.Mesh
  }
  materials: {
    Plastic: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Low.001']: THREE.MeshStandardMaterial
  }
   animations: THREE.AnimationClip[];
}

export default function ElbowModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/push-fit_90_elbow.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={102.318}>
            <mesh geometry={nodes.Low_Plastic_0.geometry} material={materials.Plastic} />
            <mesh geometry={nodes.Low_Low_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Low_Low001_0.geometry} material={materials['Low.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/push-fit_90_elbow.glb')
